
/*------------------------------------------------------------------------
    File        : ServerType
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : hdaniels
    Created     : Sat Nov 07 19:42:33 EST 2020
    Notes       : 
  ----------------------------------------------------------------------*/

enum Pmfo.Core.Common.ServerTypeEnum flags :  

    define enum Authorization
                General
                Report
                TextPlain
                Default = General
                .

end enum.