
/*------------------------------------------------------------------------
    File        : CompareStrength
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : hdaniels
    Created     : Thu Jun 24 10:43:53 EDT 2021
    Notes       : 
  ----------------------------------------------------------------------*/

enum Pmfo.Core.BusinessLogic.CompareStrengthEnum :  

    define enum RAW 
                CASE-SENSITIVE  
                CASE-INSENSITIVE 
                CAPS.

end enum.