
/*------------------------------------------------------------------------
    File        : EntityRequestTypeEnum
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : hdaniels
    Created     : Sat Jan 16 15:24:54 EST 2021
    Notes       : 
  ----------------------------------------------------------------------*/

enum Pmfo.Core.BusinessLogic.EntityRequestTypeEnum :  

    define enum Read 
                Update 
                Action .

end enum.