
/*------------------------------------------------------------------------
    File        : IDataResponse
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : hdaniels
    Created     : 2/18/2024
    Notes       : 
  ----------------------------------------------------------------------*/
 
using Pmfo.Core.BusinessLogic.IDataResponse from propath.

interface Pmfo.Core.BusinessLogic.IUpdateDataResponse inherits IDataResponse:  
end interface.