 
 /*------------------------------------------------------------------------
    File        : CharacterHandleMap
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : hdaniels
    Created     : Tue May 09 09:19:34 EDT 2023
    Notes       : 
  ----------------------------------------------------------------------*/


 
&scop classname CharacterHandleMap
&scop interface Pmfo.Core.Collections.ICharacterHandleMap
&scop keytype character
&scop keyclass Pmfo.Core.Common.CharacterHolder
&scop keyinterface Ccs.Common.Support.ICharacterHolder 
&scop valuetype handle
&scop valueinterface Ccs.Common.Support.IHandleHolder
&scop valueclass OpenEdge.Core.WidgetHandle


{Pmfo/Core/Collections/PrimitiveMap.i}
 