 
 /*------------------------------------------------------------------------
    File        : ICharacterHandleMap
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : hdaniels
    Created     : Tue May 09 09:19:34 EDT 2023
    Notes       : 
  ----------------------------------------------------------------------*/

 
&scop interfacename ICharacterHandleMap
&scop valuetype handle
&scop keytype character 
&scop valueinterface Ccs.Common.Support.IHandleHolder
&scop keyinterface Ccs.Common.Support.ICharacterHolder 

{Pmfo/Core/Collections/PrimitiveMapInterface.i}
 