
/*------------------------------------------------------------------------
    File        : ErrorTrackerEnum
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : hdaniels
    Created     : Sat Mar 30 16:27:03 EDT 2019
    Notes       : 
  ----------------------------------------------------------------------*/

enum Pmfo.Tools.AppBuilder.ErrorTrackerEnum :  

    define enum HasDynamicFunction 
                TooLongTempTableName
                AddWarningReplace
                AddMessageReplace
                IsAddOrCopyReplace.

end enum.