
/*------------------------------------------------------------------------
    File        : IClientServiceGetRequest
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : hdaniels
    Created     : Fri Aug 02 21:20:47 EDT 2019
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.
using Pmfo.Core.Service.IClientRequest.

interface Pmfo.Core.Service.IClientServiceGetRequest inherits IClientRequest:  
  
end interface.