
/*------------------------------------------------------------------------
    File        : IClientServiceUpdateRequest
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : hdaniels
    Created     : Aug 22 2020
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.
using Pmfo.Core.Service.IClientRequest.

interface Pmfo.Core.Service.IClientServiceUpdateRequest inherits IClientRequest:  
  
end interface.