
/*------------------------------------------------------------------------
    File        : IBusinessEntityCatalogBuilder
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : hdaniels
    Created     : Sat Apr 27 01:10:52 EDT 2019
    Notes       : 
  ----------------------------------------------------------------------*/
 
using Pmfo.Core.Catalog.IResourceCatalogBuilder from propath.

interface Pmfo.Core.Catalog.IBusinessEntityCatalogBuilder inherits IResourceCatalogBuilder:  
    
end interface.