 
 /*------------------------------------------------------------------------
    File        : DataSourceService
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : hdaniels
    Created     : Thu Jun 13 06:47:06 EDT 2019
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.

block-level on error undo, throw.

class Pmfo.Core.DataLayer.DataSourceService: 

end class.