
/*------------------------------------------------------------------------
    File        : ValidationHookEventType
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : hdaniels
    Created     : Wed Feb 27 16:04:48 EST 2019
    Notes       : 
  ----------------------------------------------------------------------*/

enum Pmfo.Core.DataLayer.ValidationHookEventType :  

    define enum Pre
                Begin 
                End
                Post.

end enum.